// System/Window config flags
enum WindowConfigFlag {
  FLAG_VSYNC_HINT,
  FLAG_FULLSCREEN_MODE,
  FLAG_WINDOW_RESIZABLE,
  FLAG_WINDOW_UNDECORATED,
  FLAG_WINDOW_HIDDEN,
  FLAG_WINDOW_MINIMIZED,
  FLAG_WINDOW_MAXIMIZED,
  FLAG_WINDOW_UNFOCUSED,
  FLAG_WINDOW_TOPMOST,
  FLAG_WINDOW_ALWAYS_RUN,
  FLAG_WINDOW_TRANSPARENT,
  FLAG_WINDOW_HIGHDPI,
  FLAG_MSAA_4X_HINT,
  FLAG_INTERLACED_HINT,
}
